### ISSUE TITLE
mockserver: NoSuchMethodError: org.apache.commons.lang3.builder.EqualsBuilder.setExcludeFields

### ISSUE THREAD

**Issue by iceqing** [mock-server/mockserver#1053]
**Describe the issue**
mock error when update `commons-lang3` version to 3.10

**What you are trying to do**
Description of what you are trying to do so we can understand the context of the problem

**MockServer version**
5.11.1

**To Reproduce**

update common-lang3 version to 3.10

**Expected behaviour**

**MockServer Log**
```
18:22:03.525 [MockServer-EventLog8] ERROR org.mockserver.log.MockServerEventLog - 8081 web socket server caught exception
java.lang.NoSuchMethodError: org.apache.commons.lang3.builder.EqualsBuilder.setExcludeFields([Ljava/lang/String;)Lorg/apache/commons/lang3/builder/EqualsBuilder;
	at org.mockserver.model.ObjectWithReflectiveEqualsHashCodeToString.equals(ObjectWithReflectiveEqualsHashCodeToString.java:34)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940)
	at org.mockserver.netty.unification.PortUnificationHandler.getLocalAddresses(PortUnificationHandler.java:306)
	at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:257)
	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by iceqing** [comment]
https://github.com/mock-server/mockserver/issues/817

**Comment by jamesdbloom** [comment]
This is because your project has a dependancy (potentially transitive) on a with an old version of `org.apache.commons.lang3.builder.EqualsBuilder` in in.  This method in the error above was available since version 3.6 (release 09-Jun-2017), please update this dependency to make this error go away. Or run MockServer in a [different way](https://mock-server.com/mock_server/running_mock_server.html) such as Docker container, maven plugin, etc

To understand where your dependency problem is use one of the follow commands:

### maven wrapper

```bash
./mvnw dependency:tree
```

### maven

```bash
mvn dependency:tree
```

### gradle wrapper

```bash
./gradlew -q dependencies
```

### gradle

```bash
gradle -q dependencies
```

**Comment by jamesdbloom** [comment]
Closing due to a inactivity
