### PR TITLE
Fix path parameter invalid pattern - issues: #1524, 1505

### PR DESCRIPTION
**Pull request by szada92**
Fixes issues:
- https://github.com/mock-server/mockserver/issues/1505
- https://github.com/mock-server/mockserver/issues/1524

During verification, `HttpRequestPropertiesMatcher` calls `matches` function to verify the RequestDefinition against itself - resulting the same behaviour as can be seen in newly added test, that the path parameter name will be added also as a value to the MultiValueMap. 
With this modification `PathParametersDecoder#extractPathParameters` method will not alter the stored RequestDefinition, and will not result the invalid Pattern matching for path parameter name Strings, which are not indended to be valid regex patterns.

### CODE REVIEW

**Comment by jamesdbloom** [comment]
**Rebase validation in progress**

We've rebased this PR onto the latest `master` (which now includes 12 dependency version bumps, Nashorn migration, TLS cert renewal, and other fixes) and pushed it as a test branch to validate CI:

**Rebased branch:** [`pr/1791-rebased`](https://github.com/mock-server/mockserver/tree/pr/1791-rebased)

The Buildkite pipeline will run against this rebased branch. Once results are in:
- If CI passes: we'll proceed with merging (either from this PR after you rebase, or directly from the rebased branch)
- If CI fails: we'll investigate and report back here

**Context:** We're working through all remaining open PRs to validate them against the updated codebase. Master has changed significantly — key updates include Netty 4.1.132, BouncyCastle 1.84, Tomcat 9.0.117, json-path 2.9.0, swagger-parser 2.1.22, and standalone Nashorn 15.4.

**Comment by jamesdbloom** [comment]
Merged via rebased branch `pr/1791-rebased` in commit 34e62acc4.

This PR fixes a mutation bug where `extractPathParameters()` was modifying the original `HttpRequest` object's path parameters, causing:
- **Issue #1505**: Regex pattern compilation errors (`Illegal repetition`)
- **Issue #1524**: Verification failures after upgrading to 5.14.0

The fix: Clone the `Parameters` object before mutation instead of using a direct reference.

Thank you @szada92 for identifying and fixing this bug! 🎉
